export type TicketConfig = {
  productId: string;
  creatorId: string;
  ticketType: string;
  meetGreet?: string;
  specialEntrance: string;
  merch: string;
  location?: string;
  date?: string;
  quantity: number;
  startId: number;
  endId: number;
};

export const ticketConfig: TicketConfig[] = [
  {
    productId: "prod_MBDwShu7VkcEnt",
    creatorId: "cus32fTeWz9ZBPHSnNTFxGQmHMKRVWo3QuExosk1Cev",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Austin, TX",
    date: "2022-10-27",
    quantity: 100,
    startId: 1,
    endId: 100,
  },
  {
    productId: "prod_MBEDqFgPQV2UXY",
    creatorId: "cus3UsMvYdgx7qTuVrdk1djTKr2spaRfMFTEAXR8Qka",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Austin, TX",
    date: "2022-10-27",
    quantity: 750,
    startId: 101,
    endId: 850,
  },
  {
    productId: "prod_MBE7wfHmGcOBn2",
    creatorId: "cusRxbfPwmegLZLk5zg5mpMeZq7AkSLmrQbxz2AjtR8",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Boston, MA",
    date: "2022-10-06",
    quantity: 100,
    startId: 851,
    endId: 950,
  },
  {
    productId: "prod_MBDorbLX9Q53Se",
    creatorId: "cus3zBWNqe7rDU9SwntocG7A6Ec7qtbBAcBsNT7fjAY",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Boston, MA",
    date: "2022-10-06",
    quantity: 750,
    startId: 951,
    endId: 1700,
  },
  {
    productId: "prod_M8CMtWitIFcK79",
    creatorId: "cus7RRYK1JzrehRChQGkS8bgNknC1PuK7VmAYp3uB6G",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Brooklyn, NY",
    date: "2022-09-30",
    quantity: 100,
    startId: 1701,
    endId: 1800,
  },
  {
    productId: "prod_M8Fe9OGtqRm9WA",
    creatorId: "cus7qvJLFg1bff7VFTDqmYBP2HGfLVJdQ2DGXGo5tVD",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Brooklyn, NY",
    date: "2022-09-30",
    quantity: 750,
    startId: 1801,
    endId: 2550,
  },
  {
    productId: "prod_MBE8Kc0w132sO8",
    creatorId: "cusAQrWhNFNpdKaP2QjSW6uVBaMfqzZ29o7g1B8954U",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "El Paso, TX",
    date: "2022-10-14",
    quantity: 100,
    startId: 2551,
    endId: 2650,
  },
  {
    productId: "prod_MBDqBDfZPcGU5t",
    creatorId: "cusBD56jUv5zGvywDm3KhXP8e1yWDqKZsZWT2XqwR6W",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "El Paso, TX",
    date: "2022-10-14",
    quantity: 750,
    startId: 2651,
    endId: 3400,
  },
  {
    productId: "prod_MBE33T2DGvGbbU",
    creatorId: "cusBKn8DEQmSbTD11Hi7bnieMFNEBM3KaWvxhgL3C7w",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Fresno, CA",
    date: "2022-11-17",
    quantity: 100,
    startId: 3401,
    endId: 3500,
  },
  {
    productId: "prod_MBEHk3OKTC4FpQ",
    creatorId: "cusBhYHyXTS1ERgkyEfhErukMSwiECim1985LQbGZCj",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Fresno, CA",
    date: "2022-11-17",
    quantity: 750,
    startId: 3501,
    endId: 4250,
  },
  {
    productId: "prod_MBEC7v5AAdkqE8",
    creatorId: "cusCBow7JhF9jmDv2htPWQN9tzjEbEm2RESgyBrnkRe",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Hidalgo, TX",
    date: "2022-10-23",
    quantity: 100,
    startId: 4251,
    endId: 4350,
  },
  {
    productId: "prod_MBDvdBgVCKTtpK",
    creatorId: "cusFJCi4Y7qT7gJ2ydqtEseywxidsCYnfXiNttdSsB9",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Hidalgo, TX",
    date: "2022-10-23",
    quantity: 750,
    startId: 4351,
    endId: 5100,
  },
  {
    productId: "prod_MBEBdf7OwWGwQD",
    creatorId: "cusJFhwsxbbG6P1qQ9RBxB97DRu5UDp4PgfZKqRRkjH",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Houston, TX",
    date: "2022-10-22",
    quantity: 100,
    startId: 5101,
    endId: 5200,
  },
  {
    productId: "prod_MBDuFGamFbZSEp",
    creatorId: "cusJNc86TzJriW7CB3MGnNBhug7hEHFqTJiyX73ZiSr",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Houston, TX",
    date: "2022-10-22",
    quantity: 750,
    startId: 5201,
    endId: 5950,
  },
  {
    productId: "prod_MBE4vhEtVagSUr",
    creatorId: "cusLWkCAG7a2YtYyRh3W17yFuyPcjpAQkcWjs7WbvcL",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Inglewood, CA",
    date: "2022-11-23",
    quantity: 100,
    startId: 5951,
    endId: 6050,
  },
  {
    productId: "prod_MBEJ0BuvgdoLbF",
    creatorId: "cusM3ktiMEJXKg4Rk5GWTvqPDY7X5JXD9PwFstaR3Ea",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Inglewood, CA",
    date: "2022-11-23",
    quantity: 750,
    startId: 6051,
    endId: 6800,
  },
  {
    productId: "prod_MBEAUD9WXVtdHI",
    creatorId: "cusMk324UgUYSZCWTLqbJNM95AxnTYcY3Gd1eSAPE3W",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Laredo, TX",
    date: "2022-10-20",
    quantity: 100,
    startId: 6801,
    endId: 6900,
  },
  {
    productId: "prod_MBDsYVGwSJfD3D",
    creatorId: "cusMpq6DHfFASrtPAnrbdwFJ4r49ui4A6gQpj7hvDER",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Laredo, TX",
    date: "2022-10-20",
    quantity: 750,
    startId: 6901,
    endId: 7650,
  },
  {
    productId: "prod_MBE0frl1lw8zfv",
    creatorId: "cusNPR5P9CrwSte4aMxq7xron7rMuFa1HrJPGeuF2fa",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Las Vegas, NV",
    date: "2022-11-11",
    quantity: 100,
    startId: 7651,
    endId: 7750,
  },
  {
    productId: "prod_MBEHdzgNX8ThrC",
    creatorId: "cusNkSKWc2C1PTxjVAGeZLsyvbnLKF1QhT4r1MfCCvh",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Las Vegas, NV",
    date: "2022-11-11",
    quantity: 750,
    startId: 7751,
    endId: 8500,
  },
  {
    productId: "prod_MBE5JWDwXWurKp",
    creatorId: "cusPnB9Zuz8RJe9PfFUYHmwq1yQPpGm3tsfFU2qMV7p",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Miami, FL",
    date: "2022-12-09",
    quantity: 100,
    startId: 8501,
    endId: 8600,
  },
  {
    productId: "prod_MBEJq2gpBVvkLq",
    creatorId: "cusQQmw4CwLeSoWxQYmSrZn7cijLSVaqrqUAkggazXZ",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Miami, FL",
    date: "2022-12-09",
    quantity: 750,
    startId: 8601,
    endId: 9350,
  },
  {
    productId: "prod_MBE9y5QOLhkaG8",
    creatorId: "cusR2SXJc1SHouxokzfS9xn4wJnLiyU4noKWbqJAuip",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Midland, TX",
    date: "2022-10-15",
    quantity: 100,
    startId: 9351,
    endId: 9450,
  },
  {
    productId: "prod_MBDrBtCaZLpuBw",
    creatorId: "cusRvsLs68EU2iMTtEjPbyqWMM3kiGvNDjG5v67DGhz",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Midland, TX",
    date: "2022-10-15",
    quantity: 750,
    startId: 9451,
    endId: 10200,
  },
  {
    productId: "prod_MBE9AmzyNqY3Sy",
    creatorId: "cusSBPVGHkaTGbap4SXJk5mqqJmSZxqaSPqJSr5xhLV",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Oklahoma City, OK",
    date: "2022-10-16",
    quantity: 100,
    startId: 10201,
    endId: 10300,
  },
  {
    productId: "prod_MBDseqDGl0j1np",
    creatorId: "cusSJpgkXwFBHotLgrWRDkhVSQqBFUVcEJrKqZitMB7",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Oklahoma City, OK",
    date: "2022-10-16",
    quantity: 750,
    startId: 10301,
    endId: 11050,
  },
  {
    productId: "prod_MBDzSgNhn0XYeY",
    creatorId: "cusSkLjkqMAL7phNbWg7z75nyWNsQzwiVPXMCHNvR9r",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Ontario, CA",
    date: "2022-11-10",
    quantity: 100,
    startId: 11051,
    endId: 11150,
  },
  {
    productId: "prod_MBEGgZB7ASeqEF",
    creatorId: "cusV5Tc3P7FDEQge46sMPYne9CioJLbF8QLLwFT2zE5",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Ontario, CA",
    date: "2022-11-10",
    quantity: 750,
    startId: 11151,
    endId: 11900,
  },
  {
    productId: "prod_MBDw8Hz2nz8hsE",
    creatorId: "cusWNwsUBjyy2onDzWMV5jQoqRgx29b82FtJWm85v6X",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Phoenix, AZ",
    date: "2022-10-29",
    quantity: 100,
    startId: 11901,
    endId: 12000,
  },
  {
    productId: "prod_MBED80DHPr0PHQ",
    creatorId: "cusXZxDNSmNt2rLkXApHnUQmpXwf9i29VR7YbnCKLH6",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Phoenix, AZ",
    date: "2022-10-29",
    quantity: 750,
    startId: 12001,
    endId: 12750,
  },
  {
    productId: "prod_MBDyRCYWNAwiU4",
    creatorId: "cuscdzrzMS5VukVSM4utt59oU7ooaJp2ossHLQeU3Vz",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Portland, OR",
    date: "2022-11-05",
    quantity: 100,
    startId: 12751,
    endId: 12850,
  },
  {
    productId: "prod_MBEFs7FB3hvJ8E",
    creatorId: "cusdtnPCEjJqwEHkA5aGcUsuqEUXNfsfmXDYqsyeo4w",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Portland, OR",
    date: "2022-11-05",
    quantity: 750,
    startId: 12851,
    endId: 13600,
  },
  {
    productId: "prod_MBE7S4aMWWsiOP",
    creatorId: "cuse2rx1gKyESJKGSNeTCSkrFdSGbHQgDth4ucgxuJP",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Reading, PA",
    date: "2022-10-02",
    quantity: 100,
    startId: 13601,
    endId: 13700,
  },
  {
    productId: "prod_MBDiU9cuvop3qQ",
    creatorId: "cusgZbAYdRLpenZxx6UacxyQT86X3HcWQF2MMGtCDxA",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Reading, PA",
    date: "2022-10-02",
    quantity: 750,
    startId: 13701,
    endId: 14450,
  },
  {
    productId: "prod_MBE83Ckmy2E2bv",
    creatorId: "cusgwfVKTsQBFt8FHat8oGQmYy8HKGnniVez4aL3tb2",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Rosemont, IL",
    date: "2022-10-09",
    quantity: 100,
    startId: 14451,
    endId: 14550,
  },
  {
    productId: "prod_MBDpbIhEJqq0RD",
    creatorId: "cushmQQPv3diGVugTQ1d9CoZFnnmWju1YgXTzfg5UkS",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Rosemont, IL",
    date: "2022-10-09",
    quantity: 750,
    startId: 14551,
    endId: 15300,
  },
  {
    productId: "prod_MBE5wpZmuv5CGf",
    creatorId: "cusi6VypLDs6F4wugDCxwEBpvGCBbx9iYVvrNJEz6rk",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Sacramento, CA",
    date: "2022-11-26",
    quantity: 100,
    startId: 15301,
    endId: 15400,
  },
  {
    productId: "prod_MBEJeoXtPQcbnj",
    creatorId: "cusiUmr6BCmegcW2TzBatCF93dEx63LtYPRrPHMkT6r",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Sacramento, CA",
    date: "2022-11-26",
    quantity: 750,
    startId: 15401,
    endId: 16150,
  },
  {
    productId: "prod_MBE4dBmcZlAndz",
    creatorId: "cusjDBk7q5jwz7kQWArvQXdYGcrSKDJ4QLZH9Uz2H61",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Salt Lake City, UT",
    date: "2022-11-19",
    quantity: 100,
    startId: 16151,
    endId: 16250,
  },
  {
    productId: "prod_MBEIhLgadwd7Oe",
    creatorId: "cusjgydE9xuRnM9a8wRTRtp4XuMeNUSsyhUcNtMgJJ6",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Salt Lake City, UT",
    date: "2022-11-19",
    quantity: 750,
    startId: 16251,
    endId: 17000,
  },
  {
    productId: "prod_MBEB0UL9xEXjBM",
    creatorId: "cusk9erbs9VQBCKT6RogVZ6wBy72ABwNLPNRkdz7Y1H",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Antonio, TX",
    date: "2022-10-21",
    quantity: 100,
    startId: 17001,
    endId: 17100,
  },
  {
    productId: "prod_MBDtP7Jc9KqdxD",
    creatorId: "cuskTS5YKrWNN6ZGDwqhJG2zF8QyANvnoWTgjULb3Rc",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Antonio, TX",
    date: "2022-10-21",
    quantity: 750,
    startId: 17101,
    endId: 17850,
  },
  {
    productId: "prod_MBDxtyrxevDy90",
    creatorId: "cusn9tbCzkcbf1Wrckekhx9xBUecvG24RQSQaVNFyoZ",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Diego, CA",
    date: "2022-10-30",
    quantity: 100,
    startId: 17851,
    endId: 17950,
  },
  {
    productId: "prod_MBEEwR682cZ1xg",
    creatorId: "cusnmrduUfKxC9T9i9PEZ2s6QzsG8za947fFan2ivZC",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Diego, CA",
    date: "2022-10-30",
    quantity: 750,
    startId: 17951,
    endId: 18700,
  },
  {
    productId: "prod_MBE1esUlyUkhmG",
    creatorId: "cusoLMiLQqFyFZbfHXAYHqHPH1ezoRgUsJVJQUey1j6",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Jose, CA",
    date: "2022-11-12",
    quantity: 100,
    startId: 18701,
    endId: 18800,
  },
  {
    productId: "prod_MBEHq3A1Dr8V31",
    creatorId: "cuspHaPLdVswuUP8ortYZrm3vBNtp5iWwqP281NzoK1",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "San Jose, CA",
    date: "2022-11-12",
    quantity: 750,
    startId: 18801,
    endId: 19550,
  },
  {
    productId: "prod_MBDzti9Oyg1U9L",
    creatorId: "cusuEgsBZ9ThXV5MSHQm2jiLvdrGqV3UeuHy3QhGS2J",
    ticketType: "Ozuna Tour 2022 - M&G VIP Ticket",
    meetGreet: "Unclaimed",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Seattle, WA",
    date: "2022-11-06",
    quantity: 100,
    startId: 19551,
    endId: 19650,
  },
  {
    productId: "prod_MBEFErEtBOD1SG",
    creatorId: "cusuRWeaLeW2ofRLpbQL5oHcPNY5ec6sY8dN6vzgPDZ",
    ticketType: "Ozuna Tour 2022 - VIP Ticket",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    location: "Seattle, WA",
    date: "2022-11-06",
    quantity: 750,
    startId: 19651,
    endId: 20400,
  },
  {
    productId: "prod_M8Fgi5HKecg0Zq",
    creatorId: "cusxL1PVqkEvbbcBJ9g5ueAjZKYupwdNDDoUQYEwpxQ",
    ticketType: "Ozuna North America 2022  - Digital Merch Pack",
    specialEntrance: "Unclaimed",
    merch: "Unclaimed",
    quantity: 750,
    startId: 20401,
    endId: 21150,
  },
];
